spring.ai.ollama.enabled=false

spring.ai.openai.chat.options.model=gpt-5.2
#spring.ai.openai.chat.options.temperature=0.7
#spring.ai.openai.chat.options.max-tokens=1000
spring.ai.openai.chat.options.max-completion-tokens=1000
spring.ai.openai.image.model=gpt-image-1
spring.ai.openai.image.options.response-format=b64_json
spring.ai.openai.api-key=${OPENAI_API_KEY}